#!/bin/sh

NAME="$1"
NAME=`basename "$NAME" .js`
NAME=`basename "$NAME" -resolver`

cat <<EOF
var tomahawkShim = require('./songlocator-tomahawk-shim');
var Tomahawk = tomahawkShim.Tomahawk;
var TomahawkResolver = tomahawkShim.TomahawkResolver;
var window = tomahawkShim.window;
var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
EOF

cat $1 | iconv -t utf-8 -c | sed -E \
  "s/Tomahawk\.addTrackResults/((typeof that === 'undefined')?this:that).addTrackResults/g"

cat <<EOF
exports.Resolver = Tomahawk.resolver.instance;
if (window !== undefined) {
  window.SongLocator = window.SongLocator || {};
  window.SongLocator.Tomahawk = window.SongLocator.Tomahawk || {};
  window.SongLocator.Tomahawk.$NAME = {Resolver: exports.Resolver};
}
EOF
